import Head from "next/head";
import styles from "@/styles/Home.module.css";
import List from "@/components/List";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Grid Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <List url="https://jsonplaceholder.typicode.com/posts/1/comments" />
        </div>
      </main>
    </>
  );
}
